name: xray-test

services:
  xray-php-8.0:
    container_name: xray-php-8.0
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.0"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true

  xray-php-8.1:
    container_name: xray-php-8.1
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.1"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true

  xray-php-8.2:
    container_name: xray-php-8.2
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.2"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true

  xray-php-8.3:
    container_name: xray-php-8.3
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.3"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true

  xray-php-8.4:
    container_name: xray-php-8.4
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.4"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true

  xray-php-8.5:
    container_name: xray-php-8.5
    build:
      dockerfile: "./Dockerfile"
      args:
        PHP_VERSION: "8.5"
    volumes:
      - ./:/xray
    working_dir: /xray
    user: xray
    stdin_open: true
    tty: true
