name: Unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        php_version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Start PHP ${{ matrix.php_version }} docker container
        run: |
          docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERTOKEN }}
          docker compose up -d xray-php-${{ matrix.php_version }}
          docker exec -u root xray-php-${{ matrix.php_version }} rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

      - name: Install dependencies
        run: |
          rm -rf vendor
          chmod ugo+rw .
          docker exec xray-php-${{ matrix.php_version }} composer update

      - name: Run unit tests
        run: |
          docker exec xray-php-${{ matrix.php_version }} ./vendor/bin/phpunit --configuration ./phpunit-php-${{ matrix.php_version }}.xml --testsuite 'full-suite' --do-not-cache-result ./tests
